import { useState, useEffect } from 'react';
import { Receipt, ChevronRight, Search } from 'lucide-react';
import { Link } from 'react-router-dom';
import api from '../../services/api';
import toast from 'react-hot-toast';

const STATUS_INFO = {
  PAID: { label: 'Paid', cls: 'badge-paid' },
  UNPAID: { label: 'Unpaid', cls: 'badge-unpaid' },
  OVERDUE: { label: 'Overdue', cls: 'badge-overdue' },
  PENDING_VERIFICATION: { label: 'Pending Review', cls: 'badge-pending' },
  PARTIALLY_PAID: { label: 'Partially Paid', cls: 'badge-partial' },
};

export default function TenantInvoices() {
  const [invoices, setInvoices] = useState([]);
  const [loading, setLoading] = useState(true);
  const [search, setSearch] = useState('');
  const [filter, setFilter] = useState('');

  useEffect(() => {
    api.get('/portal/invoices')
      .then(({ data }) => setInvoices(data))
      .catch(() => toast.error('Failed to load invoices'))
      .finally(() => setLoading(false));
  }, []);

  const filtered = invoices.filter(inv => {
    const matchSearch = !search ||
      (inv.unit_number || '').toLowerCase().includes(search.toLowerCase()) ||
      (inv.property_name || '').toLowerCase().includes(search.toLowerCase());
    const matchFilter = !filter || inv.status === filter;
    return matchSearch && matchFilter;
  });

  const formatMonth = (d) => d ? new Date(d).toLocaleDateString('en-GB', { month: 'long', year: 'numeric' }) : '—';
  const formatDate = (d) => d ? new Date(d).toLocaleDateString('en-GB', { day: '2-digit', month: 'short', year: 'numeric' }) : '—';

  const totalOutstanding = invoices
    .filter(i => i.status !== 'PAID')
    .reduce((s, i) => s + Number(i.balance_remaining || 0), 0);

  return (
    <div>
      <div className="page-header">
        <div>
          <h1 className="page-title">My Invoices</h1>
          <p className="page-subtitle">View and pay your monthly rent invoices</p>
        </div>
        {totalOutstanding > 0 && (
          <div style={{
            background: 'rgba(244,63,94,0.08)', border: '1px solid rgba(244,63,94,0.2)',
            borderRadius: 10, padding: '8px 16px', display: 'flex', alignItems: 'center', gap: 8,
          }}>
            <span style={{ color: 'var(--accent-rose)', fontSize: '0.85rem', fontWeight: 700 }}>
              ৳{totalOutstanding.toLocaleString()} outstanding
            </span>
          </div>
        )}
      </div>

      <div className="table-container">
        <div className="table-header">
          <h3 className="table-title">Invoice History</h3>
          <div style={{ display: 'flex', gap: 10, alignItems: 'center' }}>
            <div className="tabs">
              {[
                { value: '', label: 'All' },
                { value: 'UNPAID', label: 'Unpaid' },
                { value: 'PENDING_VERIFICATION', label: 'Pending' },
                { value: 'PARTIALLY_PAID', label: 'Partial' },
                { value: 'PAID', label: 'Paid' },
                { value: 'OVERDUE', label: 'Overdue' },
              ].map(({ value, label }) => (
                <button
                  key={value}
                  className={`tab-btn ${filter === value ? 'active' : ''}`}
                  onClick={() => setFilter(value)}
                >
                  {label}
                </button>
              ))}
            </div>
            <div className="search-bar">
              <Search size={15} color="var(--text-muted)" />
              <input
                placeholder="Search…"
                value={search}
                onChange={(e) => setSearch(e.target.value)}
              />
            </div>
          </div>
        </div>

        <table className="data-table">
          <thead>
            <tr>
              <th>Billing Month</th>
              <th>Unit</th>
              <th>Base Rent</th>
              <th>Utilities</th>
              <th>Total Due</th>
              <th>Paid</th>
              <th>Balance</th>
              <th>Due Date</th>
              <th>Status</th>
              <th style={{ textAlign: 'right' }}>Action</th>
            </tr>
          </thead>
          <tbody>
            {loading ? (
              [1, 2, 3].map(i => (
                <tr key={i}>{[1, 2, 3, 4, 5, 6, 7, 8, 9, 10].map(j => (
                  <td key={j}><div className="skeleton" style={{ height: 18, width: '80%' }} /></td>
                ))}</tr>
              ))
            ) : filtered.length === 0 ? (
              <tr><td colSpan={10}>
                <div className="empty-state">
                  <Receipt size={36} className="empty-icon" />
                  <div className="empty-title">No invoices found</div>
                  <div className="empty-desc">Your invoices will appear here when generated by your landlord.</div>
                </div>
              </td></tr>
            ) : filtered.map((inv) => {
              const { label, cls } = STATUS_INFO[inv.status] || { label: inv.status, cls: 'badge-pending' };
              const balance = Number(inv.balance_remaining || 0);
              return (
                <tr key={inv.id}>
                  <td style={{ fontWeight: 700 }}>{formatMonth(inv.billing_month)}</td>
                  <td style={{ color: 'var(--text-secondary)', fontSize: '0.83rem' }}>
                    {inv.unit_number} · {inv.property_name}
                  </td>
                  <td className="font-mono">৳{Number(inv.base_rent).toLocaleString()}</td>
                  <td className="font-mono" style={{ color: inv.utility_charges > 0 ? 'var(--accent-amber)' : 'var(--text-muted)' }}>
                    {inv.utility_charges > 0 ? `৳${Number(inv.utility_charges).toLocaleString()}` : '—'}
                  </td>
                  <td className="font-mono font-bold">
                    ৳{Number(inv.total_calculated_due || inv.amount_due).toLocaleString()}
                  </td>
                  <td className="font-mono" style={{ color: 'var(--accent-emerald)' }}>
                    ৳{Number(inv.amount_paid).toLocaleString()}
                  </td>
                  <td className="font-mono font-bold" style={{ color: balance > 0 ? 'var(--accent-rose)' : 'var(--accent-emerald)' }}>
                    ৳{balance.toLocaleString()}
                  </td>
                  <td style={{ fontSize: '0.8rem', color: 'var(--text-secondary)' }}>
                    {formatDate(inv.due_date)}
                  </td>
                  <td><span className={`badge ${cls}`}>{label}</span></td>
                  <td style={{ textAlign: 'right' }}>
                    <Link
                      to={`/portal/invoices/${inv.id}`}
                      className="btn btn-ghost btn-sm"
                      style={{ display: 'inline-flex', gap: 4 }}
                    >
                      {inv.status !== 'PAID' ? 'Pay' : 'View'} <ChevronRight size={13} />
                    </Link>
                  </td>
                </tr>
              );
            })}
          </tbody>
        </table>
      </div>
    </div>
  );
}
